name: working with triggers
on:
  push:
    branch: main
  pull-request:
    branch: main
  schedule:
     - cron: '46 5 * * *'
  workflow-dispatch:
  
jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - name: check trigger
        run: echo "checking triggers"
