name: working with triggers
on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
     - cron: '46 5 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check trigger
        run: echo "build is triggerd"
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Delpoying application
        run: echo "Deploying application"
      
  
  
